eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
spring:
  application:
    name: gateway
zuul:
  routes:
    sso:
      path: /sso/**
      serviceId: sso
    system:
      path: /system/**
      serviceId: system
      custom-sensitive-headers: true
server:
  port: 8111