eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
spring:
  application:
    name: gateway
zuul:
  routes:
    sso:
          path: /sso/**
          serviceId: sso
    system:
          path: /system/**
          serviceId: system
          sensitive-headers: Cookie,Set-Cookie
server:
  port: 8111